#pragma config(Sensor, dgtl1,  	R_Drive_Encoder,  	sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  	L_Drive_Encoder,   	sensorQuadEncoder)
#pragma config(Sensor, dgtl7,  	R_Lift_Encoder,  	sensorQuadEncoder)
#pragma config(Sensor, dgtl9,  	L_Lift_Encoder,   	sensorQuadEncoder)
#pragma config(Sensor, dgtl11, 	Tail,           	sensorDigitalOut)
#pragma config(Sensor, dgtl12, 	Skyrise,        	sensorDigitalOut)
#pragma config(Motor,  port1,           Front_R_Drive,    tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           Back_R_Drive,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           Rightlift1,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           Rightlift2,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           intake1,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           intake2,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           Leftlift1,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           Leftlift2,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           Back_L_Drive,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          Front_L_Drive,     tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)
#include "Vex_Competition_Includes.c"

/////////////////////////////////////////////////////////////////////////////////////////////////////////
// Dynamic properties of robot

#define NATURAL_ROBOT_MASS 0.0169119        // Measured using oscillation test. m = k/(4(pi^2+ln(A1/A2)^2))
#define NATURAL_ROBOT_DAMPING 0.0946197     // Measured using Oscillation test. d = k*ln(A1/A2) /(pi^2 + ln(A1/A2)^2)

#define Base_Robot_MOI .17 // Kg-M^2
#define MOI_Conversion_Factor .05
float Robot_MOI = Base_Robot_MOI*MOI_Conversion_Factor;// + .08+0.06;

#define DEG_PER_TICK 0.2088

/////////////////////////////////////////////////////////////////////////////////////////////////////////
// Type definitions

typedef struct {
	signed char Power;
	int Target;
	signed char Target_Sign;
	int Offset;
} PD_Control;

typedef signed char Byte;

/////////////////////////////////////////////////////////////////////////////////////////////////////////
// Header files

#include "LCD.h"
#include "Auto_Drive.h"
//#include "Auto_Turn.h"
//#include "Auto_Lift.h"
#include "Tele_Drive.h"
#include "Tele_Intake.h"
#include "Tele_Lift.h"
#include "Tele_Skyrise.h"

/////////////////////////////////////////////////////////////////////////////////////////////////////////
// Source files

#include "LCD.c"
#include "Auto_Drive.c"
//#include "Auto_Turn.c"
//#include "Auto_Lift.c"
#include "Tele_Drive.c"
#include "Tele_Intake.c"
#include "Tele_Lift.c"
#include "Tele_Skyrise.c"


/////////////////////////////////////////////////////////////////////////////////////////////////////////
// Auto, Pre Auto
void pre_auton()
{
	bStopTasksBetweenModes = true;
}

task autonomous()
{
	startTask(LCD);
	startTask(Auto_Drive);
	startTask(Drive_Assist);

	Drive_Timer = 0;
	clearTimer(T1);

	Drive(100,500);
	while(Drive_Enable) {
		wait1Msec(50);
	}

	Drive(100,500);
	while(Drive_Enable) {
		wait1Msec(50);
	}

	Drive_Timer = time1(T1);
}

/////////////////////////////////////////////////////////////////////////////////////////////////////////
// User Control
task usercontrol()
{
	startTask(Joystick_Velocity_Control);
	startTask(Tele_Drive);
	startTask(Tele_Lift);
	startTask(Tele_Intake);
	startTask(Tele_Skyrise);
	startTask(LCD);

	while(true)
	{
		wait1Msec(50);
	} // while (true) {
} // task usercontrol() {
