#pragma config(Sensor, dgtl1,  	R_Drive_Encoder,  	sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  	L_Drive_Encoder,   	sensorQuadEncoder)
#pragma config(Sensor, dgtl7,  	R_Lift_Encoder,  	sensorQuadEncoder)
#pragma config(Sensor, dgtl9,  	L_Lift_Encoder,   	sensorQuadEncoder)
#pragma config(Sensor, dgtl11, 	Tail,           	sensorDigitalOut)
#pragma config(Sensor, dgtl12, 	Skyrise,        	sensorDigitalOut)
#pragma config(Motor,  port1,           Front_R_Drive,    tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           Back_R_Drive,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           Rightlift1,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           Rightlift2,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           intake1,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           intake2,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           Leftlift1,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           Leftlift2,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           Back_L_Drive,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          Front_L_Drive,     tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)
#include "Vex_Competition_Includes.c"

/////////////////////////////////////////////////////////////////////////////////////////////////////////
// Dynamic properties of robot

#define NATURAL_ROBOT_MASS 0.0169119        // Measured using oscillation test. m = k/(4(pi^2+ln(A1/A2)^2))
#define NATURAL_ROBOT_DAMPING 0.0946197     // Measured using Oscillation test. d = k*ln(A1/A2) /(pi^2 + ln(A1/A2)^2)

#define Base_Robot_MOI .17 // Kg-M^2
#define MOI_Conversion_Factor .05
float Robot_MOI = Base_Robot_MOI*MOI_Conversion_Factor;// + .08+0.06;

/////////////////////////////////////////////////////////////////////////////////////////////////////////
// Type definitions

typedef signed char Byte;

typedef struct {
	Byte Power;                                 // Maximum power value 
	int Target;                                 // Target value
	float Error[5];                             // Error array
	Byte k;                                     // Error arry index counter (tells us which element of Error is newest)
	int Offset;                                 // Error offset (for error handoff)
} PD_Control;

/////////////////////////////////////////////////////////////////////////////////////////////////////////
// Power arrays

const unsigned char Auto_Power_Array[128] = {
	0,  15, 15, 15, 15, 15, 15, 16, 16, 16,
	16, 16, 16, 16, 16, 16, 16, 16, 16, 17,
	17, 17, 17, 17, 17, 18, 18, 18, 19, 20,
	21, 22, 23, 24, 25, 26, 27, 28, 29, 30,
	31, 32, 33, 34, 35, 36, 36, 37, 38, 38,
	38, 39, 40, 40, 40, 40, 40, 41, 41, 42,
	42, 43, 43, 43, 43, 44, 45, 45, 45, 45,
	46, 46, 47, 48, 48, 49, 49, 49, 49, 50,
	51, 51, 53, 53, 53, 54, 56, 56, 56, 58,
	58, 69, 69, 69, 69, 69, 69, 69, 69, 69,
	69, 73, 73, 78, 78, 78, 79, 79, 81, 81,
	81, 81, 87, 88, 88, 88, 89, 89, 89, 94,
	94, 94, 94, 110, 119, 127, 127, 127
};

const unsigned char Tele_Power_Array[128] = {
	0,  26, 26, 27, 27, 27, 27, 27, 29, 29,
	29, 29, 29, 29, 29, 29, 29, 30, 30, 30,
	30, 30, 31, 31, 31, 31, 32, 32, 32, 32,
	32, 32, 32, 32, 33, 33, 34, 34, 34, 34,
	35, 35, 35, 36, 36, 36, 36, 37, 38, 38,
	38, 39, 40, 40, 40, 40, 40, 41, 41, 42,
	42, 43, 43, 43, 43, 44, 45, 45, 45, 45,
	46, 46, 47, 48, 48, 49, 49, 49, 49, 50,
	51, 51, 53, 53, 53, 54, 56, 56, 56, 58,
	58, 69, 69, 69, 69, 69, 69, 69, 69, 69,
	69, 73, 73, 78, 78, 78, 79, 79, 81, 81,
	81, 81, 87, 88, 88, 88, 89, 89, 89, 94,
	94, 94, 94, 110, 119, 127, 127, 127
};

/////////////////////////////////////////////////////////////////////////////////////////////////////////
// Header files

#include "LCD.h"
#include "Auto_Drive.h"
#include "Auto_Turn.h"
//#include "Auto_Lift.h"
#include "Tele_Drive.h"
#include "Tele_Intake.h"
#include "Tele_Lift.h"
#include "Tele_Skyrise.h"

/////////////////////////////////////////////////////////////////////////////////////////////////////////
// Source files

#include "LCD.c"
#include "Auto_Drive.c"
#include "Auto_Turn.c"
//#include "Auto_Lift.c"
#include "Tele_Drive.c"
#include "Tele_Intake.c"
#include "Tele_Lift.c"
#include "Tele_Skyrise.c"


/////////////////////////////////////////////////////////////////////////////////////////////////////////
// Auto, Pre Auto
void pre_auton()
{
	bStopTasksBetweenModes = true;
}

task autonomous()
{
	startTask(LCD);
	startTask(Auto_Drive);
	startTask(Auto_Turn);
	startTask(Drive_Assist);

	Drive_Timer = 0;
	clearTimer(T1);

	Turn(100,360);
	while(Turn_Enable) {
		wait1Msec(10);
	}

	wait1Msec(2000);

	Drive(100,500);
	while(Drive_Enable) {
		wait1Msec(10);
	}

	Drive_Timer = time1(T1);
}

/////////////////////////////////////////////////////////////////////////////////////////////////////////
// User Control
task usercontrol()
{
	startTask(Joystick_Velocity_Control);
	startTask(Tele_Drive);
	startTask(Tele_Lift);
	startTask(Tele_Intake);
	startTask(Tele_Skyrise);
	startTask(LCD);

	while(true)
	{
		wait1Msec(50);
	} // while (true) {
} // task usercontrol() {
